kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-other-namespaces
  namespace: appdemo
  labels:
    team: boutique-team
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
